### ISSUE TITLE
docs: fix typo

### ISSUE THREAD

**Issue by jjangga0214** [tonyfromundefined/connectionify#1]
Repo 한줄 소개에 `pagenation` 을 `pagination` 으로 바꿔야 할 것 같습니다.

P.S. 사견으로 based 는 hyphon(-) 과 같이 쓰는 것이 좋지 않은까 생각합니다. 
예) `offset based` -> `offset-based`, `page number based` -> `page-number-based`

**Comment by tonyfromundefined** [comment]
의견 감사해요! 반영했어요 ㅎㅎ
